version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Stock-Data-Rust"
s3_bucket = "my-work-general-bucket"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]