AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample rust application for Lambda
  
Resources:
  # HelloRustFunctionImage:
    # Type: AWS::Serverless::Function
    # Properties:
    #   FunctionName: HelloRustImage
    #   #Runtime: provided # Amazon Linux
    #   Role: arn:aws:iam::428694349470:role/role-lambdaexec
    #   MemorySize: 512
      
    # # イメージの場合
    #   PackageType: Image
    # # ImageConfig:
    # #    Command:
    # #      - "app.lambda_handler"
    # Metadata:
    #   Dockerfile: Dockerfile
    #   DockerContext: ./stock_data
    #   DockerTag: v1

    # Zipの場合
  HelloRustFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloRust
      #Runtime: provided # Amazon Linux
      Role: arn:aws:iam::428694349470:role/role-lambdaexec
      MemorySize: 512
      CodeUri: ./stock_data
      PackageType: Zip
      Runtime: provided.al2 # Amazon Linux 2
      Handler: bootstrap.is.real.handler
    Metadata:
      BuildMethod: makefile